export const loginIconsList = [
    {
        image:"assets/loginPage/icons/patzan.png"
    },
    {
        image:"assets/loginPage/icons/padam.png"
    },
    {
        image:"assets/loginPage/icons/lamdan.png"
    },
    {
        image:"assets/loginPage/icons/aman.png"
    },
    {
        image:"assets/loginPage/icons/8200.png"
    },
    {
        image:"assets/loginPage/icons/hatam.png"
    },
]